# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/ruby/tags/
image: "ruby:2.3"

# Cache gems in between builds
cache:
  key: "$CI_BUILD_STAGE"
  paths:
    - vendor/ruby

# This is a basic example for a gem or script which doesn't use
# services such as redis or postgres
build:
  stage: build
  script:
    - ruby -v                                              # Print out ruby version for debugging
    - gem install bundler --no-ri --no-rdoc --path vendor  # Bundler is not installed with the image
    - bundle install -j $(nproc) --path vendor             # Install dependencies into ./vendor/ruby
  artifacts:
    untracked: true
    expires_in: 1 week

# Optional - Delete if not using `rubocop`
rubocop:
  script:
  - rubocop

rails:
  # Pick zero or more services to be used on all builds.
  # Only needed when using a docker container to run your tests in.
  # Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-service
  services:
    # - mysql:latest
    # - redis:latest
    # - postgres:latest
  script:
  - bundle exec rake db:migrate
  - bundle exec rake test # If using default rake tests
  #- rspec spec          # If using rspec
