image: java:8

before_script:
  - apt-get update -yqq
  - apt-get install apt-transport-https -yqq
  # Install SBT
  - echo "deb http://dl.bintray.com/sbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list
  - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 642AC823
  - apt-get update -yqq
  - apt-get install sbt -yqq
  - sbt sbt-version

test:
  script:
    - sbt clean test
